#!/bin/sh
exec 2>&1
exec ~/work/django-postfix-admin-web/run pybin --project=web uvicorn \
        web.asgi:application \
        --host "127.0.0.2" --port "8080" \
        --workers "2" \
        --limit-max-requests "32000"
